default: &default
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: root
  password: '1'

development:
  <<: *default
  database: hkapp_development

test:
  <<: *default
  database: hkapp_test